version: '1.0.5'
services:
  mc-fmc:
    image: itzg/minecraft-server:java8
    restart: on-failure
    container_name: mc-fmc
    hostname: mc-fmc
    ports:
      - "25565:25565"
    volumes:
      - "./data:/data"
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      SERVER_NAME: "SERVER NAME"
      MOTD: "SERVER MOTD"
      ICON: "ICON PATH OR URL"
      EULA: "TRUE"
      VERSION: "1.16.5"
      TYPE: "FORGE"
      FORGEVERSION: "updating soon"
      GENERIC_PACK: "uploading soon"
      ENABLE_QUERY: "true"
      SNOOPER_ENABLED: "true"
      MEMORY: 10G
      DIFFICULTY: "hard"
      MAX_PLAYERS: 16
      MAX_WORLD_SIZE: 100000
      MAX_TICK_TIME: -1
      VIEW_DISTANCE: 8
      LEVEL_TYPE: default
      ALLOW_FLIGHT: "true"
      PVP: "true"
      ONLINE_MODE: "true"
      OPS: "OP1,OP2"
      SPAWN_PROTECTION: 32
      TZ: "INSERT TIMEZONE STRING HERE"